### ISSUE TITLE
How can I use it inside of the dotnet core

### ISSUE THREAD

**Issue by oceanho** [nunit/nunit-vs-testgenerator#12] opened 2016-06-03 10:26 UTC
Hi, i have a .net core project ,i can't find 'Create IntelliTest' when i right click inside a Public class code.
It doesn't support The  .net core ?

**Comment by rprouse** [comment] 2016-06-04 15:29
I am not seeing any of the test generation options in a .NET Core project either. I expect that IntelliTest doesn't work with DNX. Visual Studio Test adapters for .NET core have a completely different interface and the alpha for the MSTest test adapter was only released last week.

I don't think this is our bug, I just don't think Visual Studio supports this yet. I am going to leave this open though and mark it as blocked. We can revisit it later if anyone can provide more information.

**Comment by oceanho** [comment] 2016-06-07 15:37
@rprouse . Yea. I don't think is a bug. it's only Visual Studio unsupports this yet. Thanks for your help.

**Comment by pvlakshm** [comment] 2016-06-09 09:19
Thank you for reporting this. You are correct, this is not a bug. The Test generators are not yet supported for .NET Core.

**Comment by OsirisTerje** [comment] 2017-01-02 09:25
I am closing this, as there is nothing we can do here.  When Microsoft releases support for .net core we will revisit this, if needed.

**Closed as completed by OsirisTerje** 2017-01-02 09:25 UTC
Labels: is:enhancement, status:blocked, pri:normal, vs_followup
